# -*- coding: utf-8 -*-
"""CBLIGHT-WOA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_abheP8-5DxC_8lf4L9IW5SYW8qdu56e
"""

import pandas as pd
import numpy as np
import scipy.linalg

# Patch scipy.linalg.triu for gensim compatibility
if not hasattr(scipy.linalg, 'triu'):
    scipy.linalg.triu = np.triu

data = pd.read_excel('./../dataset lengkap.xlsx')
data

data = data.fillna(0)
data

"""#menghapus kolom No"""

df = data.drop(columns=['No'])
df

# cleaning untuk data numerik, menghapus satuan pada dataset (ml,kg,l,kj)
import re
import numpy as np

nutrisi_cols = ['Kemasan', 'Energi', 'Lemak', 'Karbohidrat', 'Gula',
                'Protein', 'Garam', 'Natrium Benzoat']

def hapus_satuan_dan_bersihkan(val):
    if isinstance(val, str):
        val = re.sub(r'[^\d.,-]', '', val)         # hapus karakter selain angka, koma, titik, minus
        val = re.sub(r'(?<!^)-', '', val)          # hilangkan minus di tengah (bukan minus negatif)
        val = val.replace(',', '.')                # ganti koma menjadi titik
        try:
            return float(val)
        except ValueError:
            return np.nan
    return val

# Terapkan ke kolom nutrisi
for col in nutrisi_cols:
    df[col] = df[col].apply(hapus_satuan_dan_bersihkan)

#tampilkan data
df

from sklearn.preprocessing import MinMaxScaler

# ============================
# NORMALISASI MIN-MAX
# ============================

# Pastikan kolom numerik sama seperti tahap cleaning
numeric_cols = [
    "Kemasan", "Energi", "Lemak", "Karbohidrat",
    "Gula", "Protein", "Garam", "Natrium Benzoat"
]

# Inisialisasi scaler
scaler = MinMaxScaler()

# Proses normalisasi
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Cek hasil
print("Normalisasi Min-Max selesai ✅")
print(df[numeric_cols].head())

# SET TAMPILAN
# =========================
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)            # auto sesuai layar
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)  # jangan pindah baris
pd.set_option('display.float_format', '{:.5f}'.format)

# =========================
# TAMPILKAN DATA
# =========================
df[numeric_cols]

# =========================
# ENCODING LABEL MANUAL
# =========================

label_col = "Resiko"

mapping_manual = {
    "aman": 0,
    "sedang": 1,
    "tinggi": 2
}

# pastikan lowercase agar cocok
df[label_col] = df[label_col].str.lower()

df["Resiko_enc"] = df[label_col].map(mapping_manual)

# =========================
# SET TAMPILAN SUPER LEBAR
# =========================
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)

# =========================
# TAMPILKAN HASIL
# =========================

df[[label_col, "Resiko_enc"]]

# =========================
# SET TAMPILAN LEBAR
# =========================
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.float_format', '{:.5f}'.format)

# =========================
# URUTAN KOLOM SESUAI PERMINTAAN
# =========================
ordered_cols = [
    "Kemasan", "Energi", "Lemak", "Karbohidrat",
    "Gula", "Protein", "Garam", "Natrium Benzoat",
    "Komposisi", "Resiko", "Resiko_enc"
]

# Pastikan hanya kolom yang ada yang ditampilkan
ordered_cols = [c for c in ordered_cols if c in df.columns]

# =========================
# TAMPILKAN DATAFRAME
# =========================
df[ordered_cols]

# =========================
# SIMPAN DATA NUMERIK HASIL PREPROCESSING
# =========================

# Ambil hanya kolom numerik yang sudah dinormalisasi
df_numeric_preprocessed = df[numeric_cols]

# Simpan ke Excel
df_numeric_preprocessed.to_excel(
    "hasil_preprocessing_data_numerik.xlsx",
    index=False
)

print("File berhasil disimpan: hasil_preprocessing_data_numerik.xlsx")

import pandas as pd
import numpy as np
import re

# LOAD DATA
data = pd.read_excel('./../dataset lengkap.xlsx')
data.columns = data.columns.str.strip()

# CLEANING TEKS
data['Komposisi_bersih'] = (
    data['Komposisi']
    .astype(str)
    .str.lower()
    .str.replace(r'[^a-z0-9\s]', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

data.loc[data['Komposisi_bersih'].isin(['', 'nan', 'none', 'null']), 'Komposisi_bersih'] = np.nan
data = data.dropna(subset=['Komposisi_bersih']).reset_index(drop=True)

# =========================
# SET TAMPILAN SEPERTI CONTOH
# =========================
pd.set_option('display.max_columns', None)      # tampilkan semua kolom
pd.set_option('display.width', 3000)            # perlebar area tampilan
pd.set_option('display.max_colwidth', None)     # teks tidak terpotong

# Tampilkan dataframe
data[['Komposisi', 'Komposisi_bersih']]

# Case folding pada hasil cleaning
data['Komposisi_casefold'] = (
    data['Komposisi_bersih']
    .astype(str)
    .str.lower()
    .str.strip()
)

# opsional: kosong/nan jadi NaN
data.loc[data['Komposisi_casefold'].isin(['', 'nan', 'none', 'null']), 'Komposisi_casefold'] = np.nan

# tampilkan seperti contoh (atas + ... + bawah)
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)
pd.set_option('display.max_colwidth', None)

data[['Komposisi_bersih', 'Komposisi_casefold']]

# ======================================
# TOKENIZING dari Komposisi_casefold
# ======================================

# pastikan kolom ada
if 'Komposisi_casefold' not in data.columns:
    raise ValueError("Kolom 'Komposisi_casefold' belum tersedia.")

# tokenisasi sederhana (split berdasarkan spasi)
data['Komposisi_token'] = data['Komposisi_casefold'].apply(lambda x: x.split())

# =========================
# SET TAMPILAN
# =========================
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)
pd.set_option('display.max_colwidth', None)

# tampilkan hasil
data[['Komposisi_casefold', 'Komposisi_token']]

import re

# pastikan kolom token ada
if 'Komposisi_token' not in data.columns:
    raise ValueError("Kolom 'Komposisi_token' belum tersedia. Jalankan tahap tokenizing dulu.")

# stopword sederhana Bahasa Indonesia (bisa Anda tambah)
stopwords_id = {
    'dan','yang','dengan','atau','pada','di','ke','dari','untuk','dalam','sebagai','oleh',
    'tanpa','agar','karena','juga','serta','ini','itu','adalah','lebih','dapat','mengandung',
    'menggunakan','mengolah','bahan','produk','perisa','aroma'
}

def filtering_tokens(tokens, min_len=3, remove_numbers=True):
    hasil = []
    for t in tokens:
        t = t.strip()
        if not t:
            continue

        # hapus token non-alfanumerik (jaga huruf/angka saja)
        t = re.sub(r'[^a-z0-9]', '', t)

        if not t:
            continue

        # hapus angka murni (opsional)
        if remove_numbers and t.isdigit():
            continue

        # hapus token terlalu pendek
        if len(t) < min_len:
            continue

        # hapus stopword
        if t in stopwords_id:
            continue

        hasil.append(t)
    return hasil

# buat kolom hasil filtering
data['Komposisi_filter'] = data['Komposisi_token'].apply(filtering_tokens)

# =========================
# TAMPILKAN HASIL (atas...bawah)
# =========================
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)
pd.set_option('display.max_colwidth', None)

data[['Komposisi_token', 'Komposisi_filter']]

import numpy as np

# Jika belum ada gensim, jalankan ini sekali:
# !pip install gensim

from gensim.models import Word2Vec

# 1) Pastikan kolom hasil filtering ada
if 'Komposisi_filter' not in data.columns:
    raise ValueError("Kolom 'Komposisi_filter' belum tersedia. Jalankan filtering dulu.")

# 2) Corpus: list of list token (hapus yang kosong)
sentences = data['Komposisi_filter'].apply(lambda x: x if isinstance(x, list) else []).tolist()
sentences = [s for s in sentences if len(s) > 0]

print("Jumlah dokumen (sentences):", len(sentences))

# 3) Train Word2Vec
w2v_size = 100      # dimensi vektor (bisa 50/100/200)
w2v_window = 5
w2v_min_count = 2
w2v_workers = 4

w2v_model = Word2Vec(
    sentences=sentences,
    vector_size=w2v_size,
    window=w2v_window,
    min_count=w2v_min_count,
    workers=w2v_workers,
    sg=1,           # sg=1 = skip-gram, sg=0 = CBOW
    epochs=30
)

print("Vocab size:", len(w2v_model.wv.index_to_key))
import os
os.makedirs("models", exist_ok=True)
w2v_model.save("models/model_w2v_komposisi.model")

# 4) Fungsi membuat vektor dokumen (mean dari vektor kata)
def document_vector(tokens, model, vector_size):
    vecs = []
    for t in tokens:
        if t in model.wv:
            vecs.append(model.wv[t])
    if len(vecs) == 0:
        return np.zeros(vector_size, dtype=float)
    return np.mean(vecs, axis=0)

# 5) Buat embedding per baris (produk)
data['Komposisi_w2v'] = data['Komposisi_filter'].apply(
    lambda toks: document_vector(toks, w2v_model, w2v_size)
)

# 6) (Opsional) Jadikan kolom vektor terpisah: w2v_0 ... w2v_99
w2v_df = pd.DataFrame(data['Komposisi_w2v'].tolist(), columns=[f"w2v_{i}" for i in range(w2v_size)])
data_w2v = pd.concat([data.reset_index(drop=True), w2v_df], axis=1)

# SET TAMPILAN
pd.set_option('display.max_rows', 20)     # tampil atas & bawah
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)
pd.set_option('display.max_colwidth', None)

# tampilkan beberapa kolom saja agar tidak terlalu panjang
data_w2v[['Komposisi_filter'] + [f"w2v_{i}" for i in range(10)]]

import numpy as np
import pandas as pd
import re
from gensim.models import Word2Vec

# 1) LOAD DATA NUMERIK HASIL PREPROCESSING (MINMAX)
# =========================
df_num = pd.read_excel("hasil_preprocessing_data_numerik.xlsx")  # (n, n_num)

# 2) LOAD DATA TEKS (harus satu urutan baris yang sama dgn df_num)

text_col = "Komposisi"   # sesuaikan jika Anda pakai "Komposisi_bersih"
label_col = "Resiko_enc" # jika ada

# 3) LOAD MODEL WORD2VEC
# =========================
w2v_model = Word2Vec.load("word2vec_komposisi.model")
wv = w2v_model.wv
vec_dim = wv.vector_size

# 4) TOKENIZER SEDERHANA (samakan dengan preprocessing Anda kalau ada)
# =========================
def tokenize(text: str):
    if pd.isna(text):
        return []
    s = str(text).lower()
    s = re.sub(r"[^a-z0-9\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s.split()

# 5) BENTUK VEKTOR DOKUMEN (MEAN POOLING WORD2VEC)
# =========================
def doc_vector(tokens):
    valid = [wv[t] for t in tokens if t in wv.key_to_index]
    if len(valid) == 0:
        return np.zeros(vec_dim, dtype=np.float32)
    return np.mean(valid, axis=0).astype(np.float32)

# vektor word2vec per-baris (n, dim)
w2v_features = np.vstack(df[text_col].apply(lambda x: doc_vector(tokenize(x))).values)

# 6) VALIDASI JUMLAH BARIS (HARUS SAMA)
# =========================
assert df_num.shape[0] == w2v_features.shape[0], (
    f"Jumlah baris beda! numerik={df_num.shape[0]} vs w2v={w2v_features.shape[0]}. "
    "Pastikan df_num dan df teks berasal dari dataset yang sama dan urutan barisnya sama."
)

# 7) GABUNGKAN FITUR NUMERIK + WORD2VEC
# =========================
X_num = df_num.values.astype(np.float32)
X_final = np.hstack([X_num, w2v_features])  # (n, n_num + dim)

print("X_num shape      :", X_num.shape)
print("w2v_features shape:", w2v_features.shape)
print("X_final shape    :", X_final.shape)

# =========================
# 8) (OPSIONAL) BIKIN DATAFRAME GABUNGAN + SIMPAN
# =========================
w2v_cols = [f"w2v_{i}" for i in range(vec_dim)]
df_gabungan_fitur = pd.DataFrame(X_final, columns=list(df_num.columns) + w2v_cols)

# jika Anda ingin sertakan label:
if label_col in df.columns:
    df_gabungan_fitur[label_col] = df[label_col].values

df_gabungan_fitur.to_excel("fitur_gabungan_numerik_word2vec.xlsx", index=False)
print("Tersimpan: fitur_gabungan_numerik_word2vec.xlsx")

# =========================
# SET TAMPILAN
# =========================
import pandas as pd

pd.set_option('display.max_rows', 20)      # jumlah baris total yang ditampilkan
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.float_format', '{:.5f}'.format)

# =========================
# TAMPILKAN DATASET GABUNGAN
# =========================
df_gabungan_fitur

import pickle

# =========================
# SIMPAN DATASET FITUR
# =========================
with open("fitur_gabungan_numerik_word2vec.model", "wb") as f:
    pickle.dump(df_gabungan_fitur, f)

print("Data berhasil disimpan ke: fitur_gabungan_numerik_word2vec.model")

import pickle
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# 1) LOAD FILE .model (sesuaikan path)
# =========================
path_model = "fitur_gabungan_numerik_word2vec.model"  # ganti jika nama/path berbeda

with open(path_model, "rb") as f:
    df = pickle.load(f)

# =========================
# 2) AMBIL KOLOM LABEL
# =========================
label_col = "Resiko_enc"   # pastikan ini sesuai kolom Anda

# mapping manual
label_map = {0: "aman", 1: "sedang", 2: "tinggi"}

# hitung distribusi
counts = df[label_col].value_counts().sort_index()
labels = [label_map.get(int(k), str(k)) for k in counts.index]

# =========================
# 3) VISUALISASI (BAR CHART)
# =========================
plt.figure(figsize=(8, 4.5))
plt.bar(labels, counts.values)
plt.xlabel("Label")
plt.ylabel("Jumlah Data")
plt.title("Distribusi Label (Aman=0, Sedang=1, Tinggi=2)")
plt.tight_layout()
plt.show()

# =========================
# 4) TABEL RINGKAS
# =========================
summary = pd.DataFrame({
    "Label": labels,
    "Kode": counts.index.values,
    "Jumlah": counts.values
})
summary

import pickle
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from imblearn.over_sampling import RandomOverSampler

# =========================
# LOAD DATA
# =========================
with open("fitur_gabungan_numerik_word2vec.model", "rb") as f:
    df = pickle.load(f)

label_col = "Resiko_enc"
label_map = {0: "aman", 1: "sedang", 2: "tinggi"}

# =========================
# HITUNG SEBELUM
# =========================
before_counts = df[label_col].value_counts().sort_index()

# =========================
# OVERSAMPLING
# =========================
X = df.drop(columns=[label_col])
y = df[label_col]

ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X, y)

df_resampled = pd.concat(
    [pd.DataFrame(X_resampled, columns=X.columns),
     pd.Series(y_resampled, name=label_col)],
    axis=1
)

# =========================
# HITUNG SESUDAH
# =========================
after_counts = df_resampled[label_col].value_counts().sort_index()

# =========================
# SAMAKAN INDEX KELAS (0,1,2) AGAR AMAN
# =========================
all_classes = sorted(set(before_counts.index).union(set(after_counts.index)))
before_counts = before_counts.reindex(all_classes, fill_value=0)
after_counts  = after_counts.reindex(all_classes, fill_value=0)

x_labels = [label_map.get(int(c), str(c)) for c in all_classes]

# =========================
# 1 GRAFIK: GROUPED BAR (WARNA BERBEDA)
# =========================
x = np.arange(len(all_classes))
width = 0.38

plt.figure(figsize=(9, 4.8))
plt.bar(x - width/2, before_counts.values, width, label="Sebelum", color="#1f77b4")
plt.bar(x + width/2, after_counts.values,  width, label="Sesudah", color="#ff7f0e")

plt.xticks(x, x_labels)
plt.xlabel("Label")
plt.ylabel("Jumlah Data")
plt.title("Distribusi Label: Sebelum vs Sesudah Oversampling (Random Over Sampling)")
plt.legend()
plt.tight_layout()
plt.show()

import pickle

# =========================
# SIMPAN DATA OVERSAMPLING
# =========================
with open("fitur_gabungan_word2vec_oversampling.model", "wb") as f:
    pickle.dump(df_resampled, f)

print("Data oversampling berhasil disimpan sebagai: fitur_gabungan_word2vec_oversampling.model")

"""Trainning CNN-BiLSTM-LightGBM"""

import pickle
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, Model, Input
from sklearn.model_selection import train_test_split

# =========================
# 1) LOAD DATA OVERSAMPLING
# =========================
with open("fitur_gabungan_word2vec_oversampling.model", "rb") as f:
    df = pickle.load(f)

label_col = "Resiko_enc"

numeric_cols = ["Kemasan","Energi","Lemak","Karbohidrat","Gula","Protein","Garam","Natrium Benzoat"]
w2v_cols = [c for c in df.columns if c.startswith("w2v_")]

X_num = df[numeric_cols].values.astype(np.float32)
X_w2v = df[w2v_cols].values.astype(np.float32)        # (n, dim)
y     = df[label_col].values.astype(int)

n_classes = len(np.unique(y))

# =========================
# 2) SPLIT TRAIN-TEST
# =========================
Xw_train, Xw_test, Xn_train, Xn_test, y_train, y_test = train_test_split(
    X_w2v, X_num, y, test_size=0.2, random_state=42, stratify=y
)

# reshape W2V doc-vector -> "sequence" baseline: (n, dim, 1)
Xw_train_seq = Xw_train[..., np.newaxis]
Xw_test_seq  = Xw_test[..., np.newaxis]

timesteps = Xw_train_seq.shape[1]  # dim word2vec
features  = Xw_train_seq.shape[2]  # 1

# =========================
# 3) BANGUN CNN–BiLSTM (Conv1D k=3 f=64 ReLU, BiLSTM 128)
#    Output softmax hanya untuk melatih feature extractor
# =========================
text_in = Input(shape=(timesteps, features), name="text_w2v")
x = layers.Conv1D(filters=64, kernel_size=3, padding="same", activation="relu")(text_in)
x = layers.Bidirectional(layers.LSTM(128, return_sequences=False))(x)
x = layers.Dense(64, activation="relu", name="text_embed")(x)  # embedding teks

num_in = Input(shape=(Xn_train.shape[1],), name="num_in")
n = layers.Dense(32, activation="relu")(num_in)

fusion = layers.Concatenate()([x, n])
fusion = layers.Dense(64, activation="relu", name="fusion_feat")(fusion)
out = layers.Dense(n_classes, activation="softmax")(fusion)

cnn_bilstm_model = Model(inputs=[text_in, num_in], outputs=out)
cnn_bilstm_model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
cnn_bilstm_model.summary()

# =========================
# 4) TRAIN
# =========================
history = cnn_bilstm_model.fit(
    [Xw_train_seq, Xn_train], y_train,
    validation_split=0.2,
    epochs=15,
    batch_size=32,
    verbose=1
)
cnn_bilstm_model.save("models/cb1_bab3.keras")

# =========================
# 5) PREDIKSI DATA TEST
# =========================
y_pred = cnn_bilstm_model.predict([Xw_test_seq, Xn_test])
y_pred = np.argmax(y_pred, axis=1)

# =========================
# 6) VISUAL CLASSIFICATION REPORT
# =========================
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, accuracy_score

report = classification_report(y_test, y_pred, output_dict=True)
df_report = pd.DataFrame(report).transpose().round(2)

acc = accuracy_score(y_test, y_pred)

plt.figure(figsize=(8, 4))
plt.axis("off")

table = plt.table(
    cellText=df_report.values,
    colLabels=df_report.columns,
    rowLabels=df_report.index,
    cellLoc="center",
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 1.4)

plt.title(f"Classification Report CNN–BiLSTM\nAkurasi: {acc*100:.2f}%", pad=10)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history_loaded["accuracy"], label="Training Accuracy")
plt.plot(history_loaded["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training Accuracy Curve CNN–BiLSTM")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()



import numpy as np
from tensorflow.keras import Model

# =========================
# 1) BUAT FEATURE-EXTRACTOR MODEL
#    Ambil output dari layer "fusion_feat"
# =========================
feat_model = Model(
    inputs=cnn_bilstm_model.inputs,
    outputs=cnn_bilstm_model.get_layer("fusion_feat").output
)

# =========================
# 2) EKSTRAK FITUR (EMBEDDING) TRAIN & TEST
# =========================
F_train = feat_model.predict([Xw_train_seq, Xn_train], verbose=0)
F_test  = feat_model.predict([Xw_test_seq,  Xn_test],  verbose=0)

print("F_train shape:", F_train.shape)  # (n_train, dim_fitur)
print("F_test shape :", F_test.shape)   # (n_test, dim_fitur)

import lightgbm as lgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# =========================
# 1) LIGHTGBM BASELINE
# =========================
lgbm_baseline = lgb.LGBMClassifier(
    objective="multiclass",
    num_class=len(set(y_train)),
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=63,
    max_depth=-1,
    random_state=42,
    n_jobs=-1
)

lgbm_baseline.fit(F_train, y_train)

# =========================
# 2) PREDIKSI & EVALUASI
# =========================
y_pred = lgbm_baseline.predict(F_test)

acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, average="weighted")
rec  = recall_score(y_test, y_pred, average="weighted")
f1   = f1_score(y_test, y_pred, average="weighted")
cm   = confusion_matrix(y_test, y_pred)

print("=== CNN-BiLSTM-LIGHTGBM BASELINE (SOFTMAX) ===")
print(f"Accuracy  : {acc:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")
print(f"F1-Score  : {f1:.4f}")
print("Confusion Matrix:\n", cm)

# =========================
# 3) VISUAL METRIK (BAR CHART)
# =========================
metrics = ["Accuracy", "Precision", "Recall", "F1-Score"]
values  = [acc, prec, rec, f1]

plt.figure(figsize=(8, 5))
plt.bar(metrics, values)
plt.ylim(0, 1)
plt.xlabel("Metrik")
plt.ylabel("Nilai")
plt.title("Evaluasi CNN–BiLSTM–LightGBM Baseline")

for i, v in enumerate(values):
    plt.text(i, v + 0.02, f"{v:.4f}", ha="center")

plt.tight_layout()
plt.show()

# =========================
# 4) VISUAL CONFUSION MATRIX
# =========================
plt.figure(figsize=(6, 5))
plt.imshow(cm)
plt.title("Confusion Matrix - CNN–BiLSTM–LightGBM Baseline")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.colorbar()

classes = ["Aman", "Sedang", "Tinggi"]  # 0,1,2
plt.xticks(range(len(classes)), classes)
plt.yticks(range(len(classes)), classes)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.tight_layout()
plt.show()

# =========================
# 5) VISUAL CLASSIFICATION REPORT (TABEL)
# =========================
report = classification_report(y_test, y_pred, output_dict=True)
df_report = pd.DataFrame(report).transpose().round(2)

plt.figure(figsize=(8, 4))
plt.axis("off")

table = plt.table(
    cellText=df_report.values,
    colLabels=df_report.columns,
    rowLabels=df_report.index,
    cellLoc="center",
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 1.4)

plt.title(f"Classification Report\nAkurasi: {acc*100:.2f}%", pad=10)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# =========================
# 1) LEARNING CURVE (CNN–BiLSTM)
# =========================
# history = output dari cnn_bilstm_model.fit(...)

plt.figure(figsize=(8, 4.5))
plt.plot(history.history["accuracy"], label="Train Accuracy")
plt.plot(history.history["val_accuracy"], label="Val Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Learning Curve - Accuracy per Epoch (CNN–BiLSTM-LightGBM)")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4.5))
plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Learning Curve - Loss per Epoch (CNN–BiLSTM-LightGBM)")
plt.legend()
plt.tight_layout()
plt.show()

# =========================
# 2) METRIK EVALUASI (LightGBM)
# =========================
acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, average="weighted")
rec  = recall_score(y_test, y_pred, average="weighted")
f1   = f1_score(y_test, y_pred, average="weighted")

metrics = ["Accuracy", "Precision", "Recall", "F1-Score"]
values  = [acc, prec, rec, f1]

plt.figure(figsize=(8, 5))
plt.bar(metrics, values)
plt.ylim(0, 1)
plt.xlabel("Metrik")
plt.ylabel("Nilai")
plt.title("Evaluasi Model CNN–BiLSTM-LightGBM")
for i, v in enumerate(values):
    plt.text(i, v + 0.02, f"{v:.4f}", ha="center")
plt.tight_layout()
plt.show()

# =========================
# 3) CONFUSION MATRIX
# =========================
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
plt.imshow(cm)
plt.title("Confusion Matrix CNN–BiLSTM-LightGBM")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.colorbar()

# Jika label Anda 0=aman, 1=sedang, 2=tinggi
classes = ["Aman", "Sedang", "Tinggi"]
plt.xticks(range(len(classes)), classes)
plt.yticks(range(len(classes)), classes)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.tight_layout()
plt.show()

CNN-BiLSTM-LightGBM+WOA

# ====================================================
# WOA OPTIMIZATION FOR LIGHTGBM (CBLIGHT + WOA)
# ====================================================

import lightgbm as lgb
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, classification_report, confusion_matrix
from mealpy import FloatVar
from mealpy.swarm_based.WOA import OriginalWOA

# ----------------------------------------------------
# 1) SPLIT TRAIN-VAL UNTUK OPTIMASI
# ----------------------------------------------------
F_tr, F_val, y_tr, y_val = train_test_split(
    F_train, y_train,
    test_size=0.2,
    stratify=y_train,
    random_state=42
)

n_classes = len(np.unique(y_train))

# ----------------------------------------------------
# 2) OBJECTIVE FUNCTION
# ----------------------------------------------------
def objective_function(sol):

    params = {
        "objective": "multiclass",
        "num_class": n_classes,
        "num_leaves": int(sol[0]),
        "max_depth": int(sol[1]),
        "learning_rate": sol[2],
        "n_estimators": int(sol[3]),
        "random_state": 42,
        "n_jobs": -1
    }

    model = lgb.LGBMClassifier(**params)
    model.fit(F_tr, y_tr)

    pred = model.predict(F_val)
    f1 = f1_score(y_val, pred, average="weighted")

    return 1 - f1   # diminimasi

# ----------------------------------------------------
# 3) BOUNDS PARAMETER
# ----------------------------------------------------
bounds = FloatVar(
    lb=[20, -1, 0.01, 200],
    ub=[150, 12, 0.2, 800]
)

problem = {
    "bounds": bounds,
    "minmax": "min",
    "obj_func": objective_function
}

# ----------------------------------------------------
# 4) RUN WOA
# ----------------------------------------------------
print("Menjalankan optimasi WOA...")
woa = OriginalWOA(epoch=10, pop_size=10)
best = woa.solve(problem)

best_pos = best.solution
print("Best parameter WOA:", best_pos)

# ----------------------------------------------------
# 5) TRAIN FINAL MODEL CBLIGHT + WOA
# ----------------------------------------------------
best_model = lgb.LGBMClassifier(
    objective="multiclass",
    num_class=n_classes,
    num_leaves=int(best_pos[0]),
    max_depth=int(best_pos[1]),
    learning_rate=best_pos[2],
    n_estimators=int(best_pos[3]),
    random_state=42,
    n_jobs=-1
)

best_model.fit(F_train, y_train)
y_pred_woa = best_model.predict(F_test)
import joblib
joblib.dump(best_model, "models/model_lgbm_woa_bab3.joblib")



# ----------------------------------------------------
# 7) EVALUASI
# ----------------------------------------------------
print("\n=== BEST PARAMETER WOA (LightGBM) ===")
print("num_leaves    :", int(best_pos[0]))
print("max_depth     :", int(best_pos[1]))
print("learning_rate :", float(best_pos[2]))
print("n_estimators  :", int(best_pos[3]))

print("\n=== HASIL CNN-BiLSTM-LightGBM + WOA ===")
print("Accuracy:", accuracy_score(y_test, y_pred_woa))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_woa))

cm = confusion_matrix(y_test, y_pred_woa)
print("Confusion Matrix:\n", cm)

# ====================================================
# CONFUSION MATRIX
# ====================================================
y_pred_woa = best_model.predict(F_test)

cm = confusion_matrix(y_test, y_pred_woa)

classes = ["Aman", "Sedang", "Tinggi"]   # sesuaikan kelas

plt.figure(figsize=(6,5))
plt.imshow(cm)
plt.title("Confusion Matrix - CBLIGHT + WOA")
plt.colorbar()
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.xticks(range(len(classes)), classes)
plt.yticks(range(len(classes)), classes)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i,j], ha="center", va="center")

plt.tight_layout()
plt.show()

import lightgbm as lgb
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# ====================================================
# TRAIN ULANG MODEL (CBLIGHT + WOA) DENGAN EVAL METRIC
# ====================================================
evals_result = {}

best_model = lgb.LGBMClassifier(
    objective="multiclass",
    num_class=n_classes,
    num_leaves=int(best_pos[0]),
    max_depth=int(best_pos[1]),
    learning_rate=float(best_pos[2]),
    n_estimators=int(best_pos[3]),
    random_state=42,
    n_jobs=-1
)

best_model.fit(
    F_train, y_train,
    eval_set=[(F_train, y_train), (F_test, y_test)],
    eval_names=["train", "test"],
    eval_metric="multi_error",  # error rate
    callbacks=[lgb.record_evaluation(evals_result)]
)

# ====================================================
# LEARNING CURVE (ACCURACY) = 1 - multi_error
# ====================================================
train_acc = [1 - e for e in evals_result["train"]["multi_error"]]
test_acc  = [1 - e for e in evals_result["test"]["multi_error"]]

plt.figure(figsize=(8, 4.5))
plt.plot(train_acc, label="Train Accuracy")
plt.plot(test_acc, label="Test Accuracy")
plt.xlabel("Iteration")
plt.ylabel("Accuracy")
plt.title("Learning Curve - Accuracy (CBLIGHT + WOA)")
plt.ylim(0, 1)
plt.legend()
plt.tight_layout()
plt.show()

# ====================================================
# CONFUSION MATRIX
# ====================================================
y_pred_woa = best_model.predict(F_test)
cm = confusion_matrix(y_test, y_pred_woa)

classes = ["Aman", "Sedang", "Tinggi"]  # sesuaikan jumlah/urutannya

plt.figure(figsize=(6, 5))
plt.imshow(cm)
plt.title("Confusion Matrix - CBLIGHT + WOA")
plt.colorbar()
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.xticks(range(len(classes)), classes)
plt.yticks(range(len(classes)), classes)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.tight_layout()
plt.show()

# ----------------------------------------------------
# 8) VISUALISASI CLASSIFICATION REPORT (+ AKURASI %)
# ----------------------------------------------------
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, accuracy_score

# Hitung akurasi
acc = accuracy_score(y_test, y_pred_woa) * 100

# Buat classification report dalam bentuk dictionary
report_dict = classification_report(
    y_test,
    y_pred_woa,
    output_dict=True
)

df_report = pd.DataFrame(report_dict).transpose().round(4)

# Buat visualisasi tabel
plt.figure(figsize=(8, 4))
plt.axis("off")

table = plt.table(
    cellText=df_report.values,
    colLabels=df_report.columns,
    rowLabels=df_report.index,
    cellLoc="center",
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(9)
table.scale(1, 1.4)

plt.title(f"Classification Report\nCBLIGHT + WOA | Accuracy: {acc:.2f}%", pad=10)
plt.tight_layout()
plt.show()
